### ISSUE TITLE
Problems in SolidWorks

### ISSUE THREAD

**Issue by ozilxu** [OpenSourceMedicalRobots/Endo-Continuum-Robot#1]
There are some problems when implementing it in my SolidWorks:

1. The assembly can only be used for SolidWorks with a student license. Otherwise, it will show “Educational version or Instructional Use Only”.

2. There are some parts missing in the GitHub repository, for example, “55gServoAndAttachment”.

3. The “Servo Driver” part can not be shown in the assembly.

**Comment by OpenSourceMedicalRobots** [comment]
2) and 3) have been fixed in the latest update. Please pull the latest changes to see the fixes.
Regarding 1), this is an academic project hence the student license.
